(function (root) {
  "use strict";

  root.MidiWaterfallConfig = {
    MIDX_META_TYPE: 0x7F,
    MIDX_PITCHED_OFFSET_PAYLOAD_LEN: 7,
    MIDX_EXPERIMENTAL_MANUFACTURER_ID: 0x7D,
    MIDX_PITCHED_OFFSET_RECORD_TYPE: 0x03,
    OFFSET_CENT_RANGE: 64,
    OFFSET_MAGNITUDE_STEPS: 32768,
    DEFAULT_TEMPO_US_PER_QUARTER: 500000,
    MIN_PITCH: 21,
    MAX_PITCH: 108,
    NOTE_RANGE: 87,
    LOOKAHEAD_SECONDS: 6.5,
    NOTE_MIN_WIDTH: 2,
    NOTE_MAX_WIDTH: 7,
    SAME_KEY_GAP_PX: 2.5,
    SAME_KEY_TIME_EPSILON: 0.018,
    SAME_KEY_PITCH_EPSILON: 0.01,
    HIT_PARTICLE_MAX: 1200,
    HIT_PARTICLE_GRAVITY: 360,
    HIT_PARTICLE_CURSOR_EPSILON: 0.001,
    KEY_IMPACT_LIFE: 0.26,
    RULER_VELOCITY_MAX_DEPTH: 0.95,
    PREVIEW_UPDATE_CENTS: 0.1,
    PREVIEW_UPDATE_VELOCITY: 1,
    PREVIEW_VISUAL_CENTS: 18,
    PREVIEW_VISUAL_VELOCITY: 10,
    MAX_OCTAVE_DIVISIONS: 53,
    MANUAL_NOTE_FADE_DISTANCE: 620,
    MANUAL_NOTE_OFFSCREEN_MARGIN: 80,
    MANUAL_NOTE_MIN_SECONDS: 0.12,
    MANUAL_NOTE_MIN_HEIGHT: 10,
    MANUAL_NOTE_MAX: 96,
    NOTE_RENDER_LOOKBACK_SECONDS: 8
  };
})(window);
